apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
        - name: java-api
          image: localhost:32000/java-api:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.infra.svc.cluster.local:5432/usersdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "usersvc"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "usersvcpass"

            - name: SPRING_DATA_REDIS_HOST
              value: "redis.infra.svc.cluster.local"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: java-api
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: java-api
  ports:
    - port: 80
      targetPort: 8080
